on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        working-directory: ./src
        run: dotnet build --configuration Release
      - name: Test
        working-directory: ./src
        run: dotnet test --configuration Release --no-build
