on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build /src/PolymorphicSysTextJson.sln --configuration Release
      - name: Test
        run: dotnet test /src/PolymorphicSysTextJson.Tests/PolymorphicSysTextJson.Tests.csproj --configuration Release --no-build
